# Site settings
title: Stefan Thorpe
email: stefan.thorpe@gmail.com
description: A jekyll template for landing pages, portfolio and blogging

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://stefanthorpe.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
#data-ad-slot: 2973388149
#data-ad-client: ca-pub-9204963049240271
#google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-45771879-1"
addthis_id: ra-5a8633753854f0c1
#disqus_account: jeky-new-age

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/stefanthorpe
  - title: linkedin
    url: https://linkedin.com/in/stefanthorpe/
  - title: github
    url: http://github.com/stefanthorpe

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
# Build settings
